# Using numpy lib 


import numpy as np

In [15]:
km = np.loadtxt('carros-km.txt')

In [16]:
round(km.max())

119945

In [9]:
year = np.loadtxt('carros-anos.txt', dtype=int)

In [10]:
year

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

In [17]:
mean_km = km / (2021-year)

In [22]:
#Set type of mean_km
type(mean_km)



numpy.ndarray

In [24]:
mean_km

array([2.46722222e+03, 1.90400000e+02, 1.19751613e+03, 0.00000000e+00,
       1.71713333e+03, 1.19200000e+03, 0.00000000e+00, 6.46658333e+03,
       9.01790909e+03, 3.79780000e+03, 6.76789474e+02, 5.75142857e+02,
       4.48865000e+03, 0.00000000e+00, 3.45475000e+03, 2.31214000e+04,
       5.16100000e+03, 0.00000000e+00, 7.41720000e+03, 3.79325000e+03,
       5.32594737e+03, 0.00000000e+00, 3.63255556e+03, 3.43196667e+03,
       0.00000000e+00, 0.00000000e+00, 1.15900000e+03, 0.00000000e+00,
       3.09726316e+03, 3.14603333e+03, 1.25679167e+03, 2.05123077e+03,
       5.90666667e+03, 1.12693333e+03, 1.29548571e+04, 1.69134615e+03,
       0.00000000e+00, 0.00000000e+00, 4.60500000e+02, 0.00000000e+00,
       1.16768750e+04, 2.26455556e+03, 0.00000000e+00, 4.54221053e+03,
       0.00000000e+00, 5.13421053e+02, 4.11441176e+03, 1.19750000e+02,
       0.00000000e+00, 4.46383333e+03, 7.12950000e+03, 3.36640000e+03,
       3.22457143e+03, 6.26313333e+03, 3.21318182e+03, 3.00025926e+03,
      

In [28]:
mean_km_major_than_1000 =  list(filter(lambda k: k >= 1000, mean_km))

In [29]:
mean_km_major_than_1000

[2467.222222222222,
 1197.516129032258,
 1717.1333333333334,
 1192.0,
 6466.583333333333,
 9017.90909090909,
 3797.8,
 4488.65,
 3454.75,
 23121.4,
 5161.0,
 7417.2,
 3793.25,
 5325.9473684210525,
 3632.5555555555557,
 3431.9666666666667,
 1159.0,
 3097.2631578947367,
 3146.0333333333333,
 1256.7916666666667,
 2051.230769230769,
 5906.666666666667,
 1126.9333333333334,
 12954.857142857143,
 1691.3461538461538,
 11676.875,
 2264.5555555555557,
 4542.210526315789,
 4114.411764705882,
 4463.833333333333,
 7129.5,
 3366.4,
 3224.5714285714284,
 6263.133333333333,
 3213.181818181818,
 3000.259259259259,
 8536.642857142857,
 29723.75,
 4850.9,
 5045.6,
 3825.96,
 3351.6666666666665,
 2080.8571428571427,
 6070.857142857143,
 2266.4583333333335,
 1782.0666666666666,
 5541.125,
 4379.111111111111,
 8754.461538461539,
 5686.214285714285,
 3247.285714285714,
 1643.576923076923,
 23542.8,
 11388.5,
 1605.842105263158,
 9358.375,
 29940.0,
 1671.2,
 4942.076923076923,
 29553.666666666668,
 6117.555

In [38]:
print('Totals of mean of km = {} '.format(len(mean_km)))

Totals of means of km = 258 


In [39]:
print('Totals of mean km major than 1000 km = {} '.format(len(mean_km_major_than_1000)))

Totals of mean km major than 1000 km = 171 


In [40]:
print('Totals of mean km less than 1000 km = {} '.format(len(mean_km) - len(mean_km_major_than_1000)))

Totals of mean km less than 1000 km = 87 


In [75]:
list1 = [1, 'tá', 3]

In [76]:
list2 = list1.copy()

In [77]:
list2

[1, 'tá', 3]

In [78]:
list2.append('OK!')

In [79]:
list2

[1, 'tá', 3, 'OK!']

In [80]:
list1

[1, 'tá', 3]

In [81]:
list2.append(list1)

In [82]:
list2

[1, 'tá', 3, 'OK!', [1, 'tá', 3]]

In [83]:
list2[4][1]+' '+list2[3]

'tá OK!'

In [86]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
np.arange(len(mean_km_major_than_1000))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170])

In [106]:
l1 = np.array([1000,1200,1400,1600,1800,2000])
l2 = np.array([2000,2014,2011,2008,2001, 2020])

In [107]:
l1

array([1000, 1200, 1400, 1600, 1800, 2000])

In [108]:
l2

array([2000, 2014, 2011, 2008, 2001, 2020])

In [115]:
neo=l1/(2021-l2)

In [116]:
neo

array([  47.61904762,  171.42857143,  140.        ,  123.07692308,
         90.        , 2000.        ])

In [117]:
dkm = dict.fromkeys('km', for x in range neo)

SyntaxError: invalid syntax (<ipython-input-117-4da5634cb131>, line 1)

In [118]:
tp = {km: 'km' for km in neo}

In [119]:
tp

{47.61904761904762: 'km',
 171.42857142857142: 'km',
 140.0: 'km',
 123.07692307692308: 'km',
 90.0: 'km',
 2000.0: 'km'}

In [139]:
dc = dict.fromkeys(np.round(neo,decimals=0, out=None), 'km/year')

In [135]:
dc

{47.61904761904762: 'km/year',
 171.42857142857142: 'km/year',
 140.0: 'km/year',
 123.07692307692308: 'km/year',
 90.0: 'km/year',
 2000.0: 'km/year'}

In [142]:
weights = np.array([110, 89, 115, 58])

In [143]:
heights = np.array([1.74, 1.69, 1.78, 1.57])

In [144]:
imc = weights/heights**2

In [145]:
imc

array([36.33240851, 31.1613739 , 36.29592223, 23.53036634])

In [150]:
for i in range(len(imc)): 
    if(imc[i] < 25):
        print('Magro')
    elif(imc[i]> 25 and imc[i] <=30):
            print('Acima do peso')
    else:
        print('Obesidade morbida')
            

Obesidade morbida
Obesidade morbida
Obesidade morbida
Magro


In [159]:
arrays = np.array(weights)

In [160]:
arrays

array([110,  89, 115,  58])

In [161]:
arrays

array([110,  89, 115,  58])

In [173]:
arr = np.append(weights, heights)

In [174]:
arr

array([110.  ,  89.  , 115.  ,  58.  ,   1.74,   1.69,   1.78,   1.57])

In [176]:
arr = np.append(weights, heights)

In [177]:
arr

array([110.  ,  89.  , 115.  ,  58.  ,   1.74,   1.69,   1.78,   1.57])

In [179]:
arr[::2]

array([110.  , 115.  ,   1.74,   1.78])

In [180]:
arr[1::2]

array([89.  , 58.  ,  1.69,  1.57])

In [186]:
nparraye = np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

In [187]:
nparraye

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [188]:
nparraye[2,2]

9

In [194]:
nparraye[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [195]:
nparraye[nparraye > 5]

array([6, 7, 8, 9])

In [197]:
def get_pairs(obj):
    pairs = list(filter(ob: ob%2==0, obj))
    return pairs

get_pairs(nparraye)

SyntaxError: invalid syntax (<ipython-input-197-5d315e3efdeb>, line 2)

In [200]:
isinstance(nparraye.shape, tuple)

True

In [202]:
nparraye.shape


(3, 3)

In [204]:
nparraye.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [222]:
array_custom = np.append([[1, 2, 3,10], [4, 5, 6,9]], [[7, 8, 9,10]], axis=0)

In [219]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [223]:
array_custom

array([[ 1,  2,  3, 10],
       [ 4,  5,  6,  9],
       [ 7,  8,  9, 10]])

In [225]:
array_custom.reshape(4,3)

array([[ 1,  2,  3],
       [10,  4,  5],
       [ 6,  9,  7],
       [ 8,  9, 10]])

In [226]:
array_custom.sort()

In [227]:
array_custom

array([[ 1,  2,  3, 10],
       [ 4,  5,  6,  9],
       [ 7,  8,  9, 10]])

In [232]:
array_custom.resize(5,3, refcheck=False)

In [233]:
array_custom

array([[ 1,  2,  3],
       [10,  4,  5],
       [ 6,  9,  7],
       [ 8,  9, 10],
       [ 0,  0,  0]])

In [242]:
array_custom[4] = array_custom[1]**array_custom[2]

In [243]:
array_custom

array([[      1,       2,       3],
       [     10,       4,       5],
       [      6,       9,       7],
       [      8,       9,      10],
       [1000000,  262144,   78125]])

In [254]:
def pairs(some):
    return list(filter(lambda value: value%2==0, some))

In [258]:
for i in range(len(array_custom)):
    print(pairs(array_custom[i]))

[2]
[10, 4]
[6]
[8, 10]
[1000000, 262144]
